###############################################################################
# Manual exploratory DNA methylation analysis after RnBeads preprocessing
# Dataset: mouse kidney and liver at E14.5 and E15.5
#
# This script DOES NOT rerun rnb.run.analysis().
# It loads the existing rnbSet_preprocessed object made by your pipeline.
###############################################################################

###############################################################################
# 0. Load packages
###############################################################################

library(RnBeads)
library(RnBeads.mm10)

library(ggplot2)
library(pheatmap)
library(matrixStats)
library(RColorBrewer)

###############################################################################
# 1. Define paths
###############################################################################

report.dir <- "/vol/COMPEPIWS/groups/wgbs2/methylme/rnb_beads/rnbeads_reports"

plot.dir <- file.path(report.dir, "manual_plots")

dir.create(
    plot.dir,
    recursive = TRUE,
    showWarnings = FALSE
)

# Existing preprocessed object generated by your completed RnBeads pipeline
rnb.set.file <- file.path(
    report.dir,
    "rnbSet_preprocessed"
)

###############################################################################
# 2. RnBeads session settings
###############################################################################

# This affects labels/identifiers in the CURRENT R session only.
# It does not redo filtering, preprocessing, or differential methylation.
rnb.options(
    assembly = "mm10",
    identifiers.column = "sampleId"
)

###############################################################################
# 3. Load preprocessed RnBiseqSet
###############################################################################

rnb.set <- load.rnb.set(rnb.set.file)

# Obtain phenotype/sample annotation
pheno.tab <- pheno(rnb.set)

# Obtain CpG methylation beta matrix:
# rows = CpG sites
# columns = samples
beta <- meth(
    rnb.set,
    type = "sites",
    row.names = TRUE
)

# Inspect initially
print(pheno.tab)
print(colnames(pheno.tab))
print(dim(beta))
print(summarized.regions(rnb.set))

###############################################################################
# 4. Match sample annotation to methylation columns
###############################################################################

# Ensure phenotype rows are in exactly the same sample order as beta columns
pheno.tab <- pheno.tab[
    match(colnames(beta), rownames(pheno.tab)),
    ,
    drop = FALSE
]

stopifnot(identical(rownames(pheno.tab), colnames(beta)))

# Confirm that your CSV annotation fields are present
required.columns <- c(
    "sampleId",
    "tissue",
    "timepoint",
    "bedFile"
)

if (!all(required.columns %in% colnames(pheno.tab))) {
    stop(
        "Expected sample annotation columns are missing.\nFound columns: ",
        paste(colnames(pheno.tab), collapse = ", ")
    )
}

# Set biologically meaningful factor order
pheno.tab$tissue <- factor(
    pheno.tab$tissue,
    levels = c("kidney", "liver")
)

pheno.tab$timepoint <- factor(
    pheno.tab$timepoint,
    levels = c("E14.5", "E15.5")
)

# Create a combined tissue-timepoint group
pheno.tab$group <- factor(
    paste(pheno.tab$tissue, pheno.tab$timepoint, sep = "_"),
    levels = c(
        "kidney_E14.5",
        "kidney_E15.5",
        "liver_E14.5",
        "liver_E15.5"
    )
)

# Create vectors named according to the methylation-matrix column names
# This guarantees metadata stay correctly matched to methylation samples.
plot.sample.id <- pheno.tab$sampleId
names(plot.sample.id) <- colnames(beta)

tissue <- pheno.tab$tissue
names(tissue) <- colnames(beta)

timepoint <- pheno.tab$timepoint
names(timepoint) <- colnames(beta)

group <- pheno.tab$group
names(group) <- colnames(beta)

print(pheno.tab[, required.columns])
print(table(pheno.tab$tissue, pheno.tab$timepoint))

###############################################################################
# 5. Define colours used across plots
###############################################################################

tissue.cols <- c(
    kidney = "#1B9E77",
    liver = "#D95F02"
)

timepoint.cols <- c(
    "E14.5" = "#7570B3",
    "E15.5" = "#E7298A"
)

group.cols <- c(
    kidney_E14.5 = "#66C2A5",
    kidney_E15.5 = "#1B9E77",
    liver_E14.5 = "#FC8D62",
    liver_E15.5 = "#D95F02"
)

###############################################################################
# TASK 2. Manual PCA and scree plot
###############################################################################

# Retain CpGs without missing methylation values in any sample
beta.complete <- beta[
    rowSums(is.na(beta)) == 0,
    ,
    drop = FALSE
]

# Select the 10,000 CpGs with the highest variation across samples
site.sd <- matrixStats::rowSds(beta.complete)

n.pca.sites <- min(10000, nrow(beta.complete))

top.pca.indices <- order(
    site.sd,
    decreasing = TRUE
)[seq_len(n.pca.sites)]

beta.pca <- beta.complete[
    top.pca.indices,
    ,
    drop = FALSE
]

# PCA requires samples in rows and CpGs in columns
pca <- prcomp(
    t(beta.pca),
    center = TRUE,
    scale. = FALSE
)

# Percentage variance explained by each principal component
pve <- 100 * pca$sdev^2 / sum(pca$sdev^2)

pca.df <- data.frame(
    sampleId = plot.sample.id[rownames(pca$x)],
    tissue = tissue[rownames(pca$x)],
    timepoint = timepoint[rownames(pca$x)],
    group = group[rownames(pca$x)],
    PC1 = pca$x[, 1],
    PC2 = pca$x[, 2],
    row.names = rownames(pca$x)
)

p.pca <- ggplot(
    pca.df,
    aes(
        x = PC1,
        y = PC2,
        colour = tissue,
        shape = timepoint,
        label = sampleId
    )
) +
    geom_point(size = 4, alpha = 0.90) +
    geom_text(
        vjust = -0.8,
        size = 3,
        show.legend = FALSE
    ) +
    scale_colour_manual(values = tissue.cols) +
    scale_shape_manual(values = c("E14.5" = 16, "E15.5" = 17)) +
    labs(
        title = "PCA of the 10,000 most variable CpG sites",
        x = paste0("PC1 (", round(pve[1], 1), "% variance)"),
        y = paste0("PC2 (", round(pve[2], 1), "% variance)"),
        colour = "Tissue",
        shape = "Timepoint"
    ) +
    theme_classic(base_size = 14)

ggsave(
    filename = file.path(
        plot.dir,
        "PCA_top_10000_variable_CpGs.png"
    ),
    plot = p.pca,
    width = 10,
    height = 7,
    dpi = 300
)

# Scree plot: first 8 PCs because there are 8 samples
n.scree <- min(8, length(pve))

scree.df <- data.frame(
    PC = factor(seq_len(n.scree)),
    VarianceExplained = pve[seq_len(n.scree)]
)

p.scree <- ggplot(
    scree.df,
    aes(x = PC, y = VarianceExplained)
) +
    geom_col(fill = "#2C7FB8") +
    geom_text(
        aes(label = paste0(round(VarianceExplained, 1), "%")),
        vjust = -0.4,
        size = 4
    ) +
    labs(
        title = "Scree plot: variance explained by principal components",
        x = "Principal component",
        y = "Variance explained (%)"
    ) +
    coord_cartesian(
        ylim = c(0, max(scree.df$VarianceExplained) * 1.15)
    ) +
    theme_classic(base_size = 14)

ggsave(
    filename = file.path(
        plot.dir,
        "PCA_scree_plot.png"
    ),
    plot = p.scree,
    width = 9,
    height = 6,
    dpi = 300
)

###############################################################################
# TASK 3. Density plot by tissue
###############################################################################

# Work on complete sites and subsample for memory-efficient plotting
complete.site.indices <- which(rowSums(is.na(beta)) == 0)

set.seed(123)

n.density.sites <- min(
    100000,
    length(complete.site.indices)
)

density.site.indices <- sample(
    complete.site.indices,
    size = n.density.sites
)

density.df <- data.frame(
    beta = as.vector(beta[density.site.indices, , drop = FALSE]),
    tissue = rep(tissue, each = n.density.sites),
    timepoint = rep(timepoint, each = n.density.sites)
)

p.density.tissue <- ggplot(
    density.df,
    aes(x = beta, colour = tissue, fill = tissue)
) +
    geom_density(alpha = 0.20, linewidth = 0.9) +
    scale_colour_manual(values = tissue.cols) +
    scale_fill_manual(values = tissue.cols) +
    labs(
        title = "Genome-wide methylation distributions by tissue",
        x = "Methylation beta value",
        y = "Density",
        colour = "Tissue",
        fill = "Tissue"
    ) +
    theme_classic(base_size = 14)

ggsave(
    filename = file.path(
        plot.dir,
        "Density_methylation_by_tissue.png"
    ),
    plot = p.density.tissue,
    width = 10,
    height = 7,
    dpi = 300
)

# Optional additional plot: tissue distribution at each timepoint
p.density.tissue.time <- ggplot(
    density.df,
    aes(x = beta, colour = tissue, fill = tissue)
) +
    geom_density(alpha = 0.20, linewidth = 0.9) +
    facet_wrap(~timepoint) +
    scale_colour_manual(values = tissue.cols) +
    scale_fill_manual(values = tissue.cols) +
    labs(
        title = "Genome-wide methylation by tissue and timepoint",
        x = "Methylation beta value",
        y = "Density",
        colour = "Tissue",
        fill = "Tissue"
    ) +
    theme_classic(base_size = 14)

ggsave(
    filename = file.path(
        plot.dir,
        "Density_methylation_tissue_by_timepoint.png"
    ),
    plot = p.density.tissue.time,
    width = 11,
    height = 7,
    dpi = 300
)

###############################################################################
# TASK 4. Density plot by CpG-island context
###############################################################################

# Obtain site annotation for the retained CpGs
site.anno <- annotation(
    rnb.set,
    type = "sites",
    add.names = TRUE
)

# Match annotation rows to beta-matrix site order
site.anno <- site.anno[
    rownames(beta),
    ,
    drop = FALSE
]

print(colnames(site.anno))

# Find the annotation column that contains Island, Shore, Shelf, OpenSea
context.matches <- sapply(site.anno, function(x) {
    x <- as.character(x)
    sum(
        x %in% c("Island", "Shore", "Shelf", "OpenSea"),
        na.rm = TRUE
    )
})

if (max(context.matches) == 0) {
    stop(
        "Could not automatically detect the CpG-context annotation column.\n",
        "Inspect colnames(site.anno) and context.matches."
    )
}

context.column <- names(which.max(context.matches))

cat("Detected CpG-context column:", context.column, "\n")

print(table(
    site.anno[[context.column]],
    useNA = "ifany"
))

cpg.context <- as.character(site.anno[[context.column]])

valid.context <- c(
    "Island",
    "Shore",
    "Shelf",
    "OpenSea"
)

context.site.indices <- which(
    cpg.context %in% valid.context &
    rowSums(is.na(beta)) == 0
)

set.seed(123)

n.context.sites <- min(
    50000,
    length(context.site.indices)
)

context.site.indices <- sample(
    context.site.indices,
    size = n.context.sites
)

# Retain beta values from all samples, not only the mean beta per CpG.
context.df <- data.frame(
    beta = as.vector(beta[context.site.indices, , drop = FALSE]),
    context = rep(
        cpg.context[context.site.indices],
        times = ncol(beta)
    )
)

context.df$context <- factor(
    context.df$context,
    levels = c("Island", "Shore", "Shelf", "OpenSea")
)

p.density.context <- ggplot(
    context.df,
    aes(x = beta, colour = context, fill = context)
) +
    geom_density(alpha = 0.18, linewidth = 0.8) +
    labs(
        title = "DNA methylation distribution by CpG context",
        x = "Methylation beta value",
        y = "Density",
        colour = "CpG context",
        fill = "CpG context"
    ) +
    theme_classic(base_size = 14)

ggsave(
    filename = file.path(
        plot.dir,
        "Density_methylation_by_CpG_context.png"
    ),
    plot = p.density.context,
    width = 10,
    height = 7,
    dpi = 300
)

###############################################################################
# TASK 5. Heatmap of the 1,000 most variable CpG sites
###############################################################################

n.top.sites <- min(1000, nrow(beta.complete))

top.1000.indices <- order(
    site.sd,
    decreasing = TRUE
)[seq_len(n.top.sites)]

heat.sites <- beta.complete[
    top.1000.indices,
    ,
    drop = FALSE
]

# Z-score each CpG over samples to visualize relative methylation patterns.
heat.sites.z <- t(scale(t(heat.sites)))
heat.sites.z[is.na(heat.sites.z)] <- 0

sample.annotation <- data.frame(
    Tissue = tissue,
    Timepoint = timepoint,
    Group = group,
    row.names = colnames(beta)
)

pheatmap(
    heat.sites.z,
    annotation_col = sample.annotation,
    annotation_colors = list(
        Tissue = tissue.cols,
        Timepoint = timepoint.cols,
        Group = group.cols
    ),
    show_rownames = FALSE,
    show_colnames = TRUE,
    clustering_distance_cols = "euclidean",
    clustering_method = "complete",
    main = "1,000 most variable CpG sites",
    filename = file.path(
        plot.dir,
        "Heatmap_top_1000_variable_CpGs.png"
    ),
    width = 10,
    height = 12
)

###############################################################################
# TASK 6. Load and summarize mystery regions
###############################################################################

mystery.annotation.file <- paste0(
    "/vol/COMPEPIWS/data/annotation/",
    "annotation_mm10_mystery.RData"
)

# Load custom mystery-region annotation for the mm10 assembly
rnb.load.annotation(
    mystery.annotation.file,
    "mystery"
)

print(rnb.region.types("mm10"))

if (!("mystery" %in% rnb.region.types("mm10"))) {
    stop("The custom mystery annotation was not loaded successfully.")
}

# For WGBS, use coverage-weighted regional methylation summaries.
rnb.options(
    region.aggregation = "coverage.weighted"
)

# Add methylation summaries for the mystery regions to the loaded object.
rnb.set <- summarize.regions(
    rnb.set,
    region.types = "mystery"
)

print(summarized.regions(rnb.set))

# Save a NEW object; the original rnbSet_preprocessed remains unchanged.
rnb.set.mystery.file <- file.path(
    report.dir,
    "rnbSet_preprocessed_with_mystery"
)

save.rnb.set(
    rnb.set,
    rnb.set.mystery.file
)

###############################################################################
# TASK 7. Heatmap of the 100 most variable mystery regions
###############################################################################

mystery.beta <- meth(
    rnb.set,
    type = "mystery",
    row.names = TRUE
)

# Retain regions with values in all eight samples
mystery.complete <- mystery.beta[
    rowSums(is.na(mystery.beta)) == 0,
    ,
    drop = FALSE
]

mystery.sd <- matrixStats::rowSds(mystery.complete)

n.top.mystery <- min(
    100,
    nrow(mystery.complete)
)

top.100.mystery.indices <- order(
    mystery.sd,
    decreasing = TRUE
)[seq_len(n.top.mystery)]

heat.mystery <- mystery.complete[
    top.100.mystery.indices,
    ,
    drop = FALSE
]

# Z-score each region across samples
heat.mystery.z <- t(scale(t(heat.mystery)))
heat.mystery.z[is.na(heat.mystery.z)] <- 0

pheatmap(
    heat.mystery.z,
    annotation_col = sample.annotation,
    annotation_colors = list(
        Tissue = tissue.cols,
        Timepoint = timepoint.cols,
        Group = group.cols
    ),
    show_rownames = FALSE,
    show_colnames = TRUE,
    clustering_distance_cols = "euclidean",
    clustering_method = "complete",
    main = "100 most variable mystery regions",
    filename = file.path(
        plot.dir,
        "Heatmap_top_100_variable_mystery_regions.png"
    ),
    width = 10,
    height = 10
)

###############################################################################
# TASK 8. Boxplots comparing samples
###############################################################################

set.seed(123)

n.box.sites <- min(
    100000,
    length(complete.site.indices)
)

box.site.indices <- sample(
    complete.site.indices,
    size = n.box.sites
)

box.df <- data.frame(
    beta = as.vector(beta[box.site.indices, , drop = FALSE]),
    sampleId = rep(plot.sample.id, each = n.box.sites),
    tissue = rep(tissue, each = n.box.sites),
    timepoint = rep(timepoint, each = n.box.sites),
    group = rep(group, each = n.box.sites)
)

# Keep samples in the original sample-sheet order
box.df$sampleId <- factor(
    box.df$sampleId,
    levels = plot.sample.id
)

box.df$group <- factor(
    box.df$group,
    levels = c(
        "kidney_E14.5",
        "kidney_E15.5",
        "liver_E14.5",
        "liver_E15.5"
    )
)

p.boxplot.sample <- ggplot(
    box.df,
    aes(x = sampleId, y = beta, fill = tissue)
) +
    geom_boxplot(
        outlier.size = 0.15,
        outlier.alpha = 0.10,
        linewidth = 0.3
    ) +
    scale_fill_manual(values = tissue.cols) +
    labs(
        title = "Genome-wide DNA methylation by sample",
        x = "Sample",
        y = "Methylation beta value",
        fill = "Tissue"
    ) +
    theme_classic(base_size = 14) +
    theme(
        axis.text.x = element_text(
            angle = 45,
            hjust = 1
        ),
        legend.position = "top"
    )

ggsave(
    filename = file.path(
        plot.dir,
        "Boxplot_global_methylation_by_sample.png"
    ),
    plot = p.boxplot.sample,
    width = 14,
    height = 7,
    dpi = 300
)

# Optional: boxplots grouped by tissue and developmental timepoint
p.boxplot.group <- ggplot(
    box.df,
    aes(x = group, y = beta, fill = tissue)
) +
    geom_boxplot(
        outlier.size = 0.15,
        outlier.alpha = 0.10,
        linewidth = 0.3
    ) +
    scale_fill_manual(values = tissue.cols) +
    labs(
        title = "Genome-wide methylation by tissue and timepoint",
        x = "Group",
        y = "Methylation beta value",
        fill = "Tissue"
    ) +
    theme_classic(base_size = 14) +
    theme(
        axis.text.x = element_text(
            angle = 30,
            hjust = 1
        ),
        legend.position = "top"
    )

ggsave(
    filename = file.path(
        plot.dir,
        "Boxplot_global_methylation_by_group.png"
    ),
    plot = p.boxplot.group,
    width = 10,
    height = 7,
    dpi = 300
)

###############################################################################
# 9. Confirm output files
###############################################################################

print(list.files(
    plot.dir,
    full.names = TRUE
))
